### ISSUE TITLE
Button fonts and weights seem incorrect.

### ISSUE THREAD

**Issue by markbiek** [blogvault/wpcom-migration#30] opened 2024-09-06 19:09 UTC
This  might be related to the fonts but the font weight of the Continue button is heavier than the font weight of the Start migration button.

![CleanShot 2024-09-06 at 15 09 09](https://github.com/user-attachments/assets/e9d3e6ed-3166-409b-af84-3dc1c51c1949)

Can we match the style of the continue button?

**Comment by bv-shivamsharma** [comment] 2024-09-09 14:21
Works fine for me, could be a cache issue, can you try opening the wp-admin page on incognito or hit a hard refresh?

**Comment by fditrapani** [comment] 2024-09-09 16:22
I'm still seeing a difference in weight even though some other updates (like the fonts) came through. I think it might be because we're still having a font miss-match on the body. If I look at the body font in the plugin I see `-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif` compared to the app `'Open Sans', sans-serif`

**Comment by bv-shivamsharma** [comment] 2024-09-09 18:35
@fditrapani My bad completely missed that one, thanks for pointing that out. I'll get that fixed in the next iteration.

**Comment by fditrapani** [comment] 2024-09-09 18:37
Thanks @bv-shivamsharma!

**Comment by sixhours** [comment] 2024-09-10 20:31
Confirmed this has been fixed in #46!

**Closed by sixhours** 2024-09-10 20:31 UTC
Labels: Blocking, [Priority] Medium
